/**
 * ============================================================
 *  LOCAL MOCK DATA
 *  Used when VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY are
 *  not set (i.e. local development without Supabase).
 * ============================================================
 */

import {
  WorkerProfile, WorkerGig, WorkerDisbursement,
  CommissionLedger, CommissionPayout, FundingEvent,
} from '../types/database';

export const MOCK_USER_ID = 'mock-user-001';

const daysAgo  = (n: number) => new Date(Date.now() - n * 24 * 3600 * 1000).toISOString();
const daysAhead = (n: number) => new Date(Date.now() + n * 24 * 3600 * 1000).toISOString();

export const MOCK_PROFILE: WorkerProfile = {
  id:                   MOCK_USER_ID,
  full_name:            'Alex Johnson',
  phone:                '+1 555 000 1234',
  country:              'US',
  avatar_url:           null,
  badge:                'associate',
  total_gigs_completed: 7,
  total_disbursed:      14250,
  total_earned:         1567.50,
  rating:               4.6,
  onboarding_step:      'payout',
  onboarding_completed: true,
  account_health:       'healthy',
  created_at:           daysAgo(60),
  updated_at:           new Date().toISOString(),
};

export const MOCK_GIGS: WorkerGig[] = [
  {
    id: 'gig-001',
    worker_id: MOCK_USER_ID,
    client_name: 'Acme Corp',
    client_contact: 'hr@acmecorp.com',
    total_principal: 12000,
    commission_rate: 10,
    commission_amount: 1200,
    recipient_count: 6,
    disbursement_methods: ['bank_transfer', 'zelle'],
    badge_required: 'trainee',
    status: 'completed',
    deadline: daysAhead(7),
    accepted_at: daysAgo(30),
    funded_at: daysAgo(29),
    completed_at: daysAgo(5),
    funded: true,
    notes: 'Monthly contractor pay for remote team. 6 recipients.',
    created_at: daysAgo(35),
    updated_at: daysAgo(5),
  },
  {
    id: 'gig-002',
    worker_id: null,
    client_name: 'BrightPath NGO',
    client_contact: 'ops@brightpath.org',
    total_principal: 8500,
    commission_rate: 10,
    commission_amount: 850,
    recipient_count: 5,
    disbursement_methods: ['bank_transfer', 'cashapp'],
    badge_required: null,
    status: 'open',
    deadline: daysAhead(10),
    accepted_at: null,
    funded_at: null,
    completed_at: null,
    funded: false,
    notes: 'Stipend payments for field volunteers. Zelle preferred where possible.',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: 'gig-003',
    worker_id: MOCK_USER_ID,
    client_name: 'GlobalTrade Ltd',
    client_contact: 'finance@globaltrade.io',
    total_principal: 18500,
    commission_rate: 10,
    commission_amount: 1850,
    recipient_count: 8,
    disbursement_methods: ['paypal', 'bank_transfer'],
    badge_required: 'associate',
    status: 'in_progress',
    deadline: daysAhead(4),
    accepted_at: daysAgo(10),
    funded_at: daysAgo(9),
    completed_at: null,
    funded: true,
    notes: 'Vendor payments for Q3. All recipients have confirmed details.',
    created_at: daysAgo(12),
    updated_at: daysAgo(1),
  },
  {
    id: 'gig-004',
    worker_id: null,
    client_name: 'Meridian Health',
    client_contact: 'payroll@meridianhealth.com',
    total_principal: 22000,
    commission_rate: 10,
    commission_amount: 2200,
    recipient_count: 11,
    disbursement_methods: ['bank_transfer', 'zelle'],
    badge_required: 'associate',
    status: 'open',
    deadline: daysAhead(14),
    accepted_at: null,
    funded_at: null,
    completed_at: null,
    funded: false,
    notes: 'Bi-weekly payroll for part-time staff. Fast turnaround appreciated.',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: 'gig-005',
    worker_id: MOCK_USER_ID,
    client_name: 'Redwood Capital',
    client_contact: 'ops@redwoodcapital.io',
    total_principal: 5000,
    commission_rate: 10,
    commission_amount: 500,
    recipient_count: 3,
    disbursement_methods: ['bank_transfer'],
    badge_required: 'trainee',
    status: 'funded',
    deadline: daysAhead(3),
    accepted_at: daysAgo(2),
    funded_at: daysAgo(1),
    completed_at: null,
    funded: true,
    notes: 'Referral bonuses for 3 new clients. Simple gig.',
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
];

export const MOCK_DISBURSEMENTS: WorkerDisbursement[] = [
  {
    id: 'disb-001',
    gig_id: 'gig-001',
    worker_id: MOCK_USER_ID,
    recipient_name: 'Jane Smith',
    amount: 2000,
    method: 'bank_transfer',
    destination: '****4521',
    status: 'verified',
    transaction_id: 'TXN-83721',
    proof_url: null,
    notes: null,
    sent_at: daysAgo(6),
    verified_at: daysAgo(5),
    created_at: daysAgo(7),
  },
  {
    id: 'disb-002',
    gig_id: 'gig-001',
    worker_id: MOCK_USER_ID,
    recipient_name: 'Mark Osei',
    amount: 2000,
    method: 'zelle',
    destination: 'mark@email.com',
    status: 'verified',
    transaction_id: 'TXN-83722',
    proof_url: null,
    notes: null,
    sent_at: daysAgo(6),
    verified_at: daysAgo(5),
    created_at: daysAgo(7),
  },
  {
    id: 'disb-003',
    gig_id: 'gig-003',
    worker_id: MOCK_USER_ID,
    recipient_name: 'Priya Nair',
    amount: 3500,
    method: 'paypal',
    destination: 'priya@email.com',
    status: 'sent',
    transaction_id: 'TXN-91001',
    proof_url: null,
    notes: null,
    sent_at: daysAgo(1),
    verified_at: null,
    created_at: daysAgo(1),
  },
];

export const MOCK_COMMISSIONS: CommissionLedger[] = [
  {
    id: 'comm-001',
    worker_id: MOCK_USER_ID,
    gig_id: 'gig-001',
    amount: 1200,
    status: 'settled',
    settled_at: daysAgo(5),
    created_at: daysAgo(35),
  },
  {
    id: 'comm-002',
    worker_id: MOCK_USER_ID,
    gig_id: 'gig-003',
    amount: 1850,
    status: 'earned',
    settled_at: null,
    created_at: daysAgo(12),
  },
];

export const MOCK_PAYOUTS: CommissionPayout[] = [
  {
    id: 'pay-001',
    worker_id: MOCK_USER_ID,
    amount: 500,
    method: 'bank_transfer',
    destination: '****8832',
    status: 'completed',
    reference: 'PAYOUT-2026-001',
    requested_at: daysAgo(20),
    processed_at: daysAgo(18),
  },
];

export const MOCK_FUNDING_EVENTS: FundingEvent[] = [
  {
    id: 'fund-001',
    gig_id: 'gig-001',
    worker_id: MOCK_USER_ID,
    amount: 12000,
    type: 'deposit',
    reference: 'FUND-2026-0001',
    confirmed: true,
    confirmed_at: daysAgo(29),
    created_at: daysAgo(29),
  },
  {
    id: 'fund-002',
    gig_id: 'gig-003',
    worker_id: MOCK_USER_ID,
    amount: 18500,
    type: 'deposit',
    reference: 'FUND-2026-0002',
    confirmed: true,
    confirmed_at: daysAgo(9),
    created_at: daysAgo(9),
  },
  {
    id: 'fund-003',
    gig_id: 'gig-005',
    worker_id: MOCK_USER_ID,
    amount: 5000,
    type: 'deposit',
    reference: 'FUND-2026-0003',
    confirmed: true,
    confirmed_at: daysAgo(1),
    created_at: daysAgo(1),
  },
];
