import { useState } from 'react';
import { TRAINING_MODULES } from '../lib/constants';
import { Card } from '../components/ui/Card';
import { useAuth } from '../hooks/useAuth';
import { LoadingSpinner } from '../components/ui/LoadingSpinner';
import { CheckCircle, PlayCircle, Clock, BookOpen } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Modal } from '../components/ui/Modal';

const resourceContent: Record<string, React.ReactNode> = {
  'AML / OFAC Sanctions Check Guide': (
    <div className="space-y-4 text-cream/70 text-sm">
      <p>As a registered Money Services Business (MSB), PayBridge operates under strict Anti-Money Laundering (AML) and Office of Foreign Assets Control (OFAC) regulations.</p>
      <h3 className="text-cream font-bold mt-4">Your Responsibilities:</h3>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Verify Recipients:</strong> PayBridge automatically screens all recipients against OFAC sanctions lists before a gig is assigned. However, you must verify that the recipient name matches the provided instructions exactly.</li>
        <li><strong>Report Anomalies:</strong> If a recipient requests funds to be sent to a name or account not listed in the gig instructions, halt the transaction and notify Operations immediately.</li>
        <li><strong>No International Transfers:</strong> Unless explicitly stated and cleared by Operations, do not initiate cross-border transfers.</li>
      </ul>
      <p className="mt-4 p-3 rounded" style={{ background: 'rgba(239,68,68,0.1)', color: '#F87171', border: '1px solid rgba(239,68,68,0.2)' }}>Failure to comply with AML/OFAC guidelines will result in immediate account suspension and potential reporting to federal authorities.</p>
    </div>
  ),
  'Red Flags Checklist': (
    <div className="space-y-4 text-cream/70 text-sm">
      <p>Always stay vigilant. If you encounter any of the following "red flags" during a gig, pause immediately and contact Operations.</p>
      <ul className="list-none space-y-3">
        <li className="flex gap-2"><span className="text-amber-400 font-bold">⚠️</span> <span><strong>Last-minute recipient changes:</strong> The client asks you to send funds to a different name or email via direct message.</span></li>
        <li className="flex gap-2"><span className="text-amber-400 font-bold">⚠️</span> <span><strong>Split payments:</strong> Requests to break a large sum into multiple smaller transactions to avoid reporting thresholds (Structuring).</span></li>
        <li className="flex gap-2"><span className="text-amber-400 font-bold">⚠️</span> <span><strong>Overpayment refunds:</strong> Being asked to refund an "overpayment" back to a different account than the one provided.</span></li>
        <li className="flex gap-2"><span className="text-amber-400 font-bold">⚠️</span> <span><strong>Unusual urgency:</strong> High-pressure tactics demanding immediate transfers outside of standard SLA windows.</span></li>
      </ul>
    </div>
  ),
  'Proof of Disbursement Standards': (
    <div className="space-y-4 text-cream/70 text-sm">
      <p>Valid proof is required for every single transaction to earn your commission. Without valid proof, PayBridge cannot verify the gig.</p>
      <h3 className="text-cream font-bold mt-4">Acceptable Proof Formats:</h3>
      <ul className="list-disc pl-5 space-y-2">
        <li>Uncropped screenshots of the completed bank transfer, Zelle, or CashApp confirmation screen.</li>
        <li>Official PDF receipts generated by your banking institution.</li>
      </ul>
      <h3 className="text-cream font-bold mt-4">Must Include:</h3>
      <ul className="list-disc pl-5 space-y-2">
        <li>The full <strong>Transaction ID (TXID)</strong> or Reference Number.</li>
        <li>The exact <strong>Date and Time</strong> of the transfer.</li>
        <li>The full <strong>Recipient Name</strong> and/or account identifier.</li>
        <li>The exact <strong>Amount</strong> sent.</li>
      </ul>
      <p className="mt-4 p-3 rounded" style={{ background: '#0D1632', border: '1px solid rgba(241,240,218,0.1)' }}>Blurry, cropped, or edited screenshots will be automatically rejected by our compliance team.</p>
    </div>
  ),
  'Dedicated Account Policy': (
    <div className="space-y-4 text-cream/70 text-sm">
      <p>To maintain strict ledger segregation and ensure FINCEN compliance, you must use a dedicated bank account for PayBridge disbursements.</p>
      <h3 className="text-cream font-bold mt-4">Core Rules:</h3>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Zero Commingling:</strong> You may never mix personal funds with PayBridge principal funds. The account must be used <em>exclusively</em> for authorized PayBridge gigs.</li>
        <li><strong>Approved Partners Only:</strong> The account must be held at one of our 29 partnered US financial institutions.</li>
        <li><strong>Audit Readiness:</strong> You must be able to provide 90-day bank statements for this specific account upon request within 24 hours.</li>
      </ul>
      <p className="mt-4 text-xs opacity-70">Note: Your commission payouts will be sent to your separate personal payout method, not your dedicated disbursement account.</p>
    </div>
  )
};

export function TrainingPage() {
  const [selectedResource, setSelectedResource] = useState<string | null>(null);
  const { profile, isLoading } = useAuth();
  if (isLoading || !profile) return <LoadingSpinner text="Loading training..." />;

  const isComplete = profile.onboarding_completed;

  return (
    <div className="space-y-6 animate-fade-in max-w-3xl">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-black text-cream">Training Center</h1>
          <p className="text-cream/50 mt-1">Platform training modules and compliance resources</p>
        </div>
        {isComplete && <span className="status-verified">All Complete</span>}
      </div>

      {/* Status */}
      <Card padding="md" className={isComplete ? 'border-glow' : ''}>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded flex items-center justify-center"
            style={{ background: isComplete ? 'rgba(125,201,154,0.15)' : 'rgba(245,158,11,0.15)' }}>
            <BookOpen size={20} className={isComplete ? 'text-sage' : 'text-amber-400'} />
          </div>
          <div>
            <p className="font-bold text-cream text-sm">
              {isComplete ? 'Onboarding Training Complete' : 'Onboarding Training Required'}
            </p>
            <p className="text-xs text-cream/50">
              {isComplete ? 'You have completed all required training modules.' : 'Complete training to unlock the quiz and start earning.'}
            </p>
          </div>
          {!isComplete && (
            <Link to="/onboarding/training" className="ml-auto">
              <button className="btn-primary text-xs px-4 py-2">Resume →</button>
            </Link>
          )}
        </div>
      </Card>

      {/* Module cards */}
      <div className="space-y-4">
        <h2 className="font-bold text-cream">Required Modules</h2>
        {TRAINING_MODULES.map((mod, i) => (
          <Card key={mod.id} padding="md" hover>
            <div className="flex items-start gap-4">
              <div className={`w-10 h-10 rounded flex items-center justify-center font-bold text-sm flex-shrink-0 ${isComplete ? 'text-sage' : 'text-gold'}`}
                style={{ background: isComplete ? 'rgba(125,201,154,0.15)' : 'rgba(201,168,76,0.15)', border: `1px solid ${isComplete ? 'rgba(125,201,154,0.3)' : 'rgba(201,168,76,0.3)'}` }}>
                {isComplete ? <CheckCircle size={18} /> : `0${i + 1}`}
              </div>
              <div className="flex-1">
                <div className="flex items-center justify-between mb-1">
                  <h3 className="font-bold text-cream">{mod.title}</h3>
                  <span className="flex items-center gap-1 text-xs text-cream/50">
                    <Clock size={12} /> {mod.duration}
                  </span>
                </div>
                <p className="text-sm text-cream/50 mb-3">{mod.description}</p>
                {!isComplete && (
                  <Link to="/onboarding/training">
                    <button className="btn-secondary text-xs px-3 py-1.5 flex items-center gap-1.5">
                      <PlayCircle size={13} /> Watch Module
                    </button>
                  </Link>
                )}
              </div>
            </div>
          </Card>
        ))}
      </div>

      {/* Refresher resources */}
      <Card padding="md">
        <h2 className="font-bold text-cream mb-4">Ongoing Compliance Resources</h2>
        <div className="space-y-2">
          {[
            { label: 'AML / OFAC Sanctions Check Guide', note: 'Required review quarterly' },
            { label: 'Red Flags Checklist', note: 'What to watch for in every gig' },
            { label: 'Proof of Disbursement Standards', note: 'Screenshot + TXID requirements' },
            { label: 'Dedicated Account Policy', note: 'No personal transactions, ever' },
          ].map(r => (
            <div key={r.label} className="flex items-center justify-between p-3 rounded border border-white/8 hover:border-gold/20 transition-colors">
              <div>
                <p className="text-sm font-medium text-cream">{r.label}</p>
                <p className="text-xs text-cream/50">{r.note}</p>
              </div>
              <button className="btn-ghost text-xs px-3 py-1.5" onClick={() => setSelectedResource(r.label)}>View →</button>
            </div>
          ))}
        </div>
      </Card>

      <Modal isOpen={Boolean(selectedResource)} onClose={() => setSelectedResource(null)} title={selectedResource ?? 'Resource'}>
        {selectedResource && resourceContent[selectedResource]}
        <div className="mt-8 flex justify-end">
          <button className="btn-secondary px-6 py-2" onClick={() => setSelectedResource(null)}>Close Document</button>
        </div>
      </Modal>
    </div>
  );
}
